version: "3.9"

services:

  fastapi:
    build: .
    container_name: footprints_backend
    restart: always
    env_file:
        - ./.env

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8000:80"
    depends_on:
      - fastapi
