"""add spot media file

Revision ID: bac4707a7baf
Revises: 84226ce8eb1e
Create Date: 2025-09-29 09:01:22.729013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bac4707a7baf'
down_revision: Union[str, None] = '84226ce8eb1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spot_media_files',
    sa.Column('spot_id', sa.Integer(), nullable=False),
    sa.Column('media_file_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['media_file_id'], ['media_files.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['spot_id'], ['scenic_spots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('spot_id', 'media_file_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('spot_media_files')
    # ### end Alembic commands ###
